export default {
  SET_MOVIE_ID: "SET_MOVIE_ID",
  START_FETCH_MOVIES_LIST: 'START_FETCH_MOVIES_LIST',
  FETCH_MOVIES_LIST_SUCCESS: 'FETCH_MOVIES_LIST_SUCCESS',
  FETCH_MOVIES_LIST_FAILED: 'FETCH_MOVIES_LIST_FAILED',
  SET_MOVIES: "SET_MOVIES"
}
